### ISSUE TITLE
Cannot search in location because of  abag

### ISSUE THREAD

**Issue by DaliaFR** [TrustedSourceLeaks/LeakedServer#11]
![2020-06-08 11-26 _514 5, 15 3, 106 7_-0 2, -0 8, 0 5, -0 3 (0)](https://user-images.githubusercontent.com/66266619/84015440-203b0880-a97c-11ea-9356-e0c919b93500.png)

When i have this bag i cannot scavenge in the location, each time it's open the screen but objet don't open instead a new bag open and stay in inventory, and secure container disapear. 

In return of player hideout, the bags are many (like number of items scavenged) secure container came back)
When i tried to trash the bag it's impossible;

12.6 mod alllmissingkeys & allofficialloot

**Comment by trustedLeaks** [comment]
Isn't emu related, this come from the official, can't do anything about it

**Comment by DaliaFR** [comment]
Ok, my game is broken do you know if it possible to fix? Now it do this all the time
