### ISSUE TITLE
Passing wrong health object to saveHealth

### ISSUE THREAD

**Issue by KeKTapeCanFixIt** [TrustedSourceLeaks/LeakedServer#9]
https://github.com/TrustedSourceLeaks/LeakedServer/blob/2a209468caae2dbcd734555c688be9d95bfdd280/src/classes/offraid.js#L292

Shouldn't this line be passing `offraidData.health` instead?
`health_f.healthServer.saveHealth(pmcData, offraidData.health, sessionID);`

**Comment by diqiuguying** [comment]
I also think it should be "offraidData.health" .

and
https://github.com/TrustedSourceLeaks/LeakedServer/blob/2a209468caae2dbcd734555c688be9d95bfdd280/src/classes/health.js#L98-L118

Should be changed to
```
    saveHealth(pmcData, info, sessionID) {
        let nodeHealth = this.healths[sessionID];
        let nodeEffects = this.effects[sessionID];

        nodeHealth.Hydration = info.Hydration;
        nodeHealth.Energy = info.Energy;

        for (let bodyPart of Object.keys(info.Health)) {
            if (info.Health[bodyPart].Effects != undefined) { 
                nodeEffects[bodyPart] = info.Health[bodyPart].Effects;
            }

            if (info.IsAlive === true) {
                nodeHealth[bodyPart] = **info.Health**[bodyPart].Current;
            } else {
                nodeHealth[bodyPart] = -1;
            }
        }
        this.applyHealth(pmcData, sessionID);
    }
```
info.Hydration.Current => info.Hydration
info.Energy.Current => info.Energy
info.BodyParts =>info.Health

It preserves health and hunger correctly.

**Comment by trustedLeaks** [comment]
> https://github.com/TrustedSourceLeaks/LeakedServer/blob/2a209468caae2dbcd734555c688be9d95bfdd280/src/classes/offraid.js#L292
> 
> Shouldn't this line be passing `offraidData.health` instead?
> `health_f.healthServer.saveHealth(pmcData, offraidData.health, sessionID);`

No because health values are stored into offraidData.profile.Health, not in offraidData.Health

**Comment by diqiuguying** [comment]
not offraidData.Health but offraidData.health.

1 .offraidData.health
2. offraidData.profile.Health
Both have value stores,1 stores the value after the raid,2 stores the value before the raid,I did the comparison...

My English is very poor.
